// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvqswgjuuiksoxttcfct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2cXN3Z2p1dWlrc294dHRjZmN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0Njk4NzYsImV4cCI6MjA2MjA0NTg3Nn0.vdMV68CywWe6BMDWwdxQ46Qzd2IH95k6meSJ3O2ajjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);